cache: bundler

language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-head
  - rbx-2
  - ruby-head

sudo: false

bundler_args: --retry=3 --jobs=3

env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
  fast_finish: true

addons:
  code_climate:
    repo_token: 79945a23e353c668553e647df658770b978c7729fb1fa7ab69bc7cfe391d99c2
